In [1]:
import numpy as np
import pandas as pd

flight_data = pd.read_csv('/Users/xuxinyi/Downloads/sort.csv', index_col=0) # remove the index column
flight_data.head()

,i1_legid,i1_hops,i1_dep_1_place,i1_rcf_1_place,i1_rcf_1_p,i1_rcf_1_e,i1_dep_2_place,i1_rcf_2_place,i1_rcf_2_p,i1_rcf_2_e,...,lead_time,value,cargo_price_unit,weight,risk_1,risk_2,risk_3,risk_all,distance,cargo_price
0,5878,1,DOH,PVG,905,547,?,?,0,0,...,547,90059,0.52,2.49,2.0,0.0,0.0,2.0,4220.0,5464.06
1,9889,1,FRA,LHR,215,223,?,?,0,0,...,223,3786,0.40,1.25,3.0,0.0,0.0,3.0,406.0,203.00
2,3997,1,FRA,ZRH,270,135,?,?,0,0,...,135,11143,0.62,0.36,3.5,0.0,0.0,3.5,177.0,39.51
3,10481,1,FRA,CDG,285,219,?,?,0,0,...,219,8283,0.44,3.29,4.0,0.0,0.0,4.0,278.0,402.43
4,12343,1,FCO,LHR,395,152,?,?,0,0,...,152,74548,0.74,3.46,2.5,0.0,0.0,2.5,897.0,2296.68

In [2]:
#give some randomness to the risk
#import random
# flight_data['risk_1'] = flight_data['risk_1']+random.uniform(-1, 0.5)
# flight_data['risk_2'] = flight_data['risk_1']+random.uniform(-1, 0.5)
# flight_data['risk_3'] = flight_data['risk_1']+random.uniform(-1, 0.5)
# flight_data['risk_all'] = flight_data['risk_1'] + flight_data['risk_2'] + flight_data['risk_3']
#flight_data['risk_all'] = flight_data['risk_all']+random.uniform(-1, 0.5)

In [3]:
flight_data.head()

,i1_legid,i1_hops,i1_dep_1_place,i1_rcf_1_place,i1_rcf_1_p,i1_rcf_1_e,i1_dep_2_place,i1_rcf_2_place,i1_rcf_2_p,i1_rcf_2_e,...,lead_time,value,cargo_price_unit,weight,risk_1,risk_2,risk_3,risk_all,distance,cargo_price
0,5878,1,DOH,PVG,905,547,?,?,0,0,...,547,90059,0.52,2.49,2.0,0.0,0.0,2.0,4220.0,5464.06
1,9889,1,FRA,LHR,215,223,?,?,0,0,...,223,3786,0.40,1.25,3.0,0.0,0.0,3.0,406.0,203.00
2,3997,1,FRA,ZRH,270,135,?,?,0,0,...,135,11143,0.62,0.36,3.5,0.0,0.0,3.5,177.0,39.51
3,10481,1,FRA,CDG,285,219,?,?,0,0,...,219,8283,0.44,3.29,4.0,0.0,0.0,4.0,278.0,402.43
4,12343,1,FCO,LHR,395,152,?,?,0,0,...,152,74548,0.74,3.46,2.5,0.0,0.0,2.5,897.0,2296.68

In [4]:
flight_data['order_date'] = pd.to_datetime(flight_data.order_date)
flight_data['deliver_date'] = pd.to_datetime(flight_data['deliver_date'])
flight_data['planned_date'] = pd.to_datetime(flight_data['planned_date'])
flight_data.set_index('order_date', inplace=True) # after setting order_date as an index, it will not be in the column
df = flight_data.loc['2019-3-21':'2019-3-28']  # order date in the range

In [5]:
df.reset_index(level=0, inplace=True) # need to reset the index so that the order_date will be back in column
df.sort_values('order_date', inplace=True, ascending=False)
df.reset_index(level=0, inplace=True) # need to reset the index AGAIN so that the orderrange list would be the same order

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [6]:
df['from_to'] = df['origin'] + ' - '+ df['desti']

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [7]:
df.loc[:,'color'] = np.where((df['risk_all'] >= 6) & (df['value'] >= 30000), 'red', 
                            np.where((df['risk_all'] <= 3) & (df['value'] <= 60000), 'green', 'orange'))

/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:337: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/Applications/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [8]:
from bokeh.io import show, output_file, output_notebook
from bokeh.models import ColumnDataSource, SingleIntervalTicker, LinearAxis, LinearColorMapper, ColorBar
from bokeh.plotting import figure
from bokeh.models.tools import HoverTool
from bokeh.transform import transform

#output_file("iris.html", title="iris.py example")
output_notebook

source = ColumnDataSource(df)

risk_color_mapper = LinearColorMapper(palette=['#2BA743', '#F5A623', '#E90F0F'], 
                                 low=0, high=10)
value_color_mapper = LinearColorMapper(palette=['#2BA743', '#F5A623', '#E90F0F'], 
                                 low=0, high=100000)

p = figure(title = "Risk Value Chart", plot_width=800, plot_height=600,toolbar_location=None, 
           x_range=(0, 10), y_range=(0, 100000))
p.xaxis.ticker = SingleIntervalTicker(interval=1, num_minor_ticks=0)
p.xaxis.axis_label = 'Risk'
p.yaxis.axis_label = 'Value'
# p.xaxis.axis_line_width = 3
# p.xaxis.bounds = (7, 10)
# p.xaxis.axis_line_color = "red"

p.circle('risk_all','value',source=source, color='color',
         alpha=0.5, size=10)  # alpha and fill_alpha are different!

# p.scatter('risk_all','value',source=source, radius=0.05, 
#           fill_color='blue', fill_alpha=0.6,
#           line_color=None)

color_bar = ColorBar(color_mapper=risk_color_mapper, location=(0,0), orientation='horizontal')
p.add_layout(color_bar, 'below')
color_bar = ColorBar(color_mapper=value_color_mapper, location=(0,0), orientation='vertical')
p.add_layout(color_bar, 'left') 
# how to make colorbar scientific false??

p.left[0].formatter.use_scientific = False 

hover = HoverTool()
hover.tooltips = [
            ('Order number','#@i1_legid'),
            ('From to', '@from_to'),
            ('Risk', '@risk_all'),
            ('Value', '@value'),
            ('Legs', '@i1_hops'),
            ('Expected delivery time', '@deliver_date{%F}'),
           ]

hover.mode = 'mouse'
hover.formatters={'deliver_date': 'datetime'}

p.add_tools(hover)

show(p)